version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "7000:6379"
  mysql:
    image: "mysql:5.7"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3308:3306"
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
            - mysql
            - redis
